version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: strapi_user
      POSTGRES_PASSWORD: strapi_pass
      POSTGRES_DB: strapi_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  strapi:
    build: ./backend
    ports:
      - "1337:1337"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi_db
      DATABASE_USERNAME: strapi_user
      DATABASE_PASSWORD: strapi_pass
      DATABASE_SSL: "false"
    depends_on:
      - postgres

  nextjs:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  postgres-data:
